// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5NAbfggps98xg0N3wNomBtD0VG4LbgYU',
    appId: '1:703275229955:web:61a5749e2079fa3600bf36',
    messagingSenderId: '703275229955',
    projectId: 'study-app-63213',
    authDomain: 'study-app-63213.firebaseapp.com',
    storageBucket: 'study-app-63213.appspot.com',
    measurementId: 'G-GQQVKLX85M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACALBVgNN5S2F4_to3E4Dqx71aMVeCAWg',
    appId: '1:703275229955:android:fcf3b169efdaeb7800bf36',
    messagingSenderId: '703275229955',
    projectId: 'study-app-63213',
    storageBucket: 'study-app-63213.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDqZyVagEPTAtUz_Ua9WaEv6ILBF5lUO4',
    appId: '1:703275229955:ios:bc099fe8112d6f8c00bf36',
    messagingSenderId: '703275229955',
    projectId: 'study-app-63213',
    storageBucket: 'study-app-63213.appspot.com',
    iosClientId: '703275229955-emglaun4ipsp5ircm3ing9r6lkmhbpi0.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDqZyVagEPTAtUz_Ua9WaEv6ILBF5lUO4',
    appId: '1:703275229955:ios:bc099fe8112d6f8c00bf36',
    messagingSenderId: '703275229955',
    projectId: 'study-app-63213',
    storageBucket: 'study-app-63213.appspot.com',
    iosClientId: '703275229955-emglaun4ipsp5ircm3ing9r6lkmhbpi0.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyApp',
  );
}
